# Project: 輾轉相除法函式呼叫
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 輾轉相除法主程式.o
LINKOBJ  = 輾轉相除法主程式.o
LIBS     = -L"C:/Users/shane/Downloads/Dev-Cpp/MinGW64/lib" -L"C:/Users/shane/Downloads/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/shane/Downloads/Dev-Cpp/MinGW64/include" -I"C:/Users/shane/Downloads/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/shane/Downloads/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/shane/Downloads/Dev-Cpp/MinGW64/include" -I"C:/Users/shane/Downloads/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/shane/Downloads/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/shane/Downloads/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 輾轉相除法函式呼叫.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

輾轉相除法主程式.o: 輾轉相除法主程式.cpp
	$(CPP) -c 輾轉相除法主程式.cpp -o 輾轉相除法主程式.o $(CXXFLAGS)
